title: "Inayat Ullah"
email: "inayat@s3h.nust.edu.pk"
description: "Assistant Professor, Government & Public Policy, NUST Islamabad"
url: "https://inayatullahamin.github.io"
baseurl: ""

github_username: inayatullahamin
linkedin_username: inayatullahamin
scholar_userid: JwcKpJgAAAAJ
orcid_id: 0000-0003-0520-0311

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

navbar_links:
  - title: "Publications"
    url: /publications/
  - title: "Working Papers"
    url: /working-papers/
