# Site settings
title: "Inayat Ullah"
email: inayat@kdis.ac.kr
description: >-
  Personal academic website of Inayat Ullah

# Theme
remote_theme: academicpages/academicpages

# URL settings
url: "https://inayatullahamin.github.io" # your GitHub Pages URL
baseurl: "" # leave empty for user site (username.github.io)

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (only those allowed on GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

# Collections
collections:
  teaching:
    output: true
  news:
    output: true
  projects:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
